---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: install psycopg2
    yum: name={{item}}
    with_items:
        - postgresql-server
        - postgresql-contrib
        - epel-release
        - python-pip
        - python3-psycopg2
        - postgresql-devel
        - postgresql-libs
  - name: install psycopg2
    pip: name=psycopg2

  - name: start postgresql server
    service: name=postgresql state=started enabled=yes
  vars:
    dbname: myapp
    dbuser: django
    dbpassword: mysupersecretpassword

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
